title: "Abrar Zahin — ML Research Blog"
description: "Notes on Gaussian graphical models, statistical ML, agents, and computational pathology"

url: "https://zahinabrar.github.io"
baseurl: "/Abrar-Zahin-Blog"   # keep this unless you rename the repo

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.0"
minimal_mistakes_skin: "default"

# Markdown & math
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
highlighter: rouge
mathjax: true   # enable MathJax site-wide

# Plugins (you already use these)
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Archives (for /tags/ and /categories/ pages if you add them)
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    tag: archive
    category: archive
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Home shows recent posts
paginate: 10

# Make posts look like Lilian’s
defaults:
  - scope: { path: "", type: posts }
    values:
      layout: single
      classes: wide
      author_profile: false
      toc: true
      toc_sticky: true
      read_time: true
      show_date: true
      show_prev_next: false   # hide big Previous/Next bar
      mathjax: true
  - scope: { path: "", type: pages }
    values:
      layout: single
      author_profile: false

# Nice post URLs
permalink: /posts/:year-:month-:day-:title/
