title: "Abrar Zahin — ML Research Blog"
description: "Notes on Gaussian graphical models, statistical ML, agents, and computational pathology"

url: "https://zahinabrar.github.io"
baseurl: "/Abrar-Zahin-Blog"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.0"
minimal_mistakes_skin: "default"

# Markdown & math
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
highlighter: rouge
mathjax: true

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Archives (for /tags/ and /categories/)
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    tag: archive
    category: archive
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Home shows recent posts
paginate: 10
paginate_path: "/page:num/"

# Pretty post URLs
permalink: /posts/:year-:month-:day-:title/

# Defaults
defaults:
  - scope: { path: "", type: posts }
    values:
      layout: single
      author_profile: false
      toc: false          # using custom collapsible TOC in posts
      toc_sticky: false   # (disable built-in TOC)
      read_time: true
      show_date: true
      show_prev_next: false
      mathjax: true
  - scope: { path: "", type: pages }
    values:
      layout: single
      author_profile: false



