title: "Abrar’s Blog"
description: "Notes on GGMs, agents, and computational pathology"
url: "https://zahinabrar.github.io"
baseurl: "/blog"

# Minimal Mistakes (remote theme)
remote_theme: "mmistakes/minimal-mistakes@4.26.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Optional: nice permalinks for posts
permalink: /posts/:year-:month-:day-:title/
